[package]
name = "epick"
version = "0.1.0"
authors = ["wojciechkepka <wojtek.kepka@protonmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
eframe = { path = "/home/wojtek/dev/egui/eframe" }
egui = { path = "/home/wojtek/dev/egui/egui" }
epi = { path = "/home/wojtek/dev/egui/epi" }
#eframe = "*"
#egui = "0.12"
#epi = "0.12"
clipboard = "0.5"

[profile.release]
opt-level = 2
