[package]
name = "testgui"
version = "0.1.0"
authors = ["wojciechkepka <wojtek.kepka@protonmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
eframe = "*"
clipboard = "0.5"

[profile.release]
opt-level = 2
