[package]
name = "epick"
version = "0.4.0-alpha"
authors = ["wojciechkepka <wojtek.kepka@protonmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
eframe = "0.14"
egui = "0.14"
epi = "0.14"
epaint = "0.14"
clipboard = "0.5"
lazy_static = "1"
anyhow = "1"

[target.'cfg(unix)'.dependencies]
x11rb = { version = "0.9", features = ["image"] }

