[package]
name = "epick"
version = "0.3.0"
authors = ["wojciechkepka <wojtek.kepka@protonmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
eframe = { git = "https://github.com/emilk/egui" }
egui = { git = "https://github.com/emilk/egui" }
epi = { git = "https://github.com/emilk/egui" }
epaint = { git = "https://github.com/emilk/egui" }
clipboard = "0.5"
lazy_static = "1"

# workaround for wasm build https://github.com/Amanieu/parking_lot/issues/269
parking_lot_core = "=0.8.0"
