on:
  workflow_dispatch:
  push:
    paths-ignore:
      - "*.md"
      - "LICENSE"


name: epick CI

jobs:
  check:
    name: Check
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@main
      - uses: ./.github/actions/check

  fmt:
    name: Rustfmt
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@main
      - uses: ./.github/actions/fmt

  clippy:
    name: Clippy
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@main
      - uses: ./.github/actions/clippy

  test:
    name: Test Suite
    needs: [check, fmt, clippy]
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@main
      - uses: ./.github/actions/test

  test_web:
    name: Test web build
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Install dependencies
        run: sudo apt-get install libxcb-render0-dev libxcb-shape0-dev libxcb-xfixes0-dev libxkbcommon-dev
      - name: Install web build dependencies
        run: cargo install wasm-bindgen-cli
      - name: Add wasm target
        run: rustup target add wasm32-unknown-unknown
      - name: Test web build
        run: ./scripts/build_web.sh
      - name: Upload artifacts
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
